
site: SuperTu

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Supertú | Tu agencia de redes sociales
subtitle: "Hacemos de tu marca una súper marca"
description: Agencia de redes sociales en Málaga con más de 10 años de experiencia en marketing digital y comunicación. ¿Quieres convertirte en una supermarca?
url: "https://supertu.netlify.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"
permalink: /:title/

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

collections:
  team:
    output: true
  services:
    output: true
  clients:
    output: true

# Category descriptions (for archive pages)
descriptions:
  - cat: blogpost
    desc: "El blog de Super Tú"


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
 