backend:
  name: github
  repo: JaviCepa/supertu-web-netlify
  branch: master
  site_domain: supertu.netlify.com

media_folder: "/img/upload"
public_folder: "/img/upload"

collections:
  - name: "blogpost"
    label: "Blogposts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "service"
    label: "Servicios"
    folder: "_services"
    create: true
    slug: "{{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Imagen", name: "image", widget: image}
  - name: "client"
    label: "Clientes"
    folder: "_clients"
    create: true
    slug: "{{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Cita", name: "quote", widget: "string"}
      - {label: "Logo", name: "logo", widget: image}