backend:
  name: github
  repo: JaviCepa/SupertuWeb2020
  branch: master
  site_domain: supertu.es

media_folder: "/img/upload"
public_folder: "/img/upload"
site_url: https://supertu.es
logo_url: https://supertu.es/img/logo_full.svg
locale: 'es'

slug:
  clean_accents: true

collections:
  - name: "blogpost"
    label: "Blogposts"
    folder: "_posts"
    preview_path: /blog/{{slug}}
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Título (H1)", name: "title", widget: "string"}
      - {label: "Subtítulo (H2)", name: "subtitle", widget: "string"}
      - {label: "URL", name: "permalink", widget: "string", required: true, default: "blog/", hint: "Debe empezar por 'blog/' (sin comillas) y tener este formato 'blog/como-pasar-accion-redes-sociales' (sin acentos y omitiendo preposiciones)", pattern: ['.{12,}', "Tiene que tener por lo menos 12 caracteres."]}
      - label: "Categorías"
        name: "tags"
        widget: "relation"
        collection: "tags"
        valueField: "tag"
        searchFields: ["tag"]
        multiple: true
        required: false
      - label: "Autor"
        name: "author"
        widget: "relation"
        collection: "teammember"
        valueField: "name"
        searchFields: ["name"]
      - {label: "Fecha", name: "date", widget: "datetime", required: false, hint: "La fecha a mostrar en el post. Si no se define se usará la fecha de creación (no la de última modificación)."}
      - {label: "Oculto", name: "hidden", widget: "boolean", required: false, hint: "Puedes marcar el post como oculto si quieres publicarlo más adelante."}
      - label: "Imagen"
        name: "image"
        widget: "image"
        required: false
        hint: "El tamaño máximo de las imagenes que se pueden subir es de ~500kb (unos 0.5MB) por temas de optimización de tiempo de carga."
        media_library:
            config:
                max_file_size: 512000
      - label: "Miniatura RRSS"
        name: "social_media_image"
        widget: "image"
        required: false
        hint: "Esta imagen es la que se insertará al compartir el enlace en redes sociales (si no hay ninguna definida se usará la imagen del post)"
        media_library:
            config:
                max_file_size: 512000
      - {label: "Contenido", name: "body", widget: "markdown", required: false}
      - {label: "SEO Title", name: "seotitle", widget: "string", required: false, hint: "Irá dentro del head y será el título mostrado en la barra del navegador."}
      - {label: "SEO Description", name: "description", widget: "string", required: false, hint: "Irá dentro de la etiqueta de meta-descripción del head."}
      - {label: "SEO Keywords", name: "keywords", widget: "string", required: false}
  - name: "teammember"
    label: "Equipo"
    folder: "_team"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "teammember", required: false}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Oculto", name: "hidden", widget: "boolean", required: false, hint: "Puedes marcar este miembro como oculto si quieres publicarlo más adelante."}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Teléfono", name: "telephone", widget: "string", required: false}
      - {label: "Cargo", name: "position", widget: "string", required: false}
      - {label: "Cita", name: "quote", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Orden", name: "order", widget: "hidden", required: false}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "SEO Custom URL", name: "permalink", widget: "string", required: false}
      - {label: "SEO Title", name: "seotitle", widget: "string", required: false, hint: "Irá dentro del head y será el título mostrado en la barra del navegador."}
      - {label: "SEO Keywords", name: "keywords", widget: "string", required: false}
  - name: "client"
    label: "Clientes"
    folder: "_clients"
    create: true
    slug: "{{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Logo", name: "logo", widget: image}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "SEO Custom URL", name: "permalink", widget: "string", required: false}
      - {label: "SEO Title", name: "seotitle", widget: "string", required: false, hint: "Irá dentro del head y será el título mostrado en la barra del navegador."}
      - {label: "SEO Keywords", name: "keywords", widget: "string", required: false}
  - name: "services"
    label: "Servicios"
    folder: "_services"
    create: true
    slug: "{{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Orden", name: "order", widget: "string"}
      - {label: "Icono", name: "icon", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "URL", name: "permalink", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "SEO Title", name: "seotitle", widget: "string", required: false, hint: "Irá dentro del head y será el título mostrado en la barra del navegador."}
      - {label: "SEO Keywords", name: "keywords", widget: "string", required: false}
  - name: "tags"
    label: "Categorías"
    folder: "_tags"
    create: true
    identifier_files: tag
    fields:
      - {label: "Nombre", name: "tag", widget: "string"}
      - {label: "SEO Custom URL", name: "permalink", widget: "string", required: false}
      - {label: "SEO Title", name: "seotitle", widget: "string", required: false}
      - {label: "SEO Description", name: "description", widget: "string", required: false}
      - {label: "SEO Keywords", name: "keywords", widget: "string", required: false}